<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-26T12:28:16 IST" name="Default suite" finished-at="2023-11-26T12:29:00 IST" duration-ms="43384">
    <groups>
    </groups>
    <test started-at="2023-11-26T12:28:16 IST" name="Default test" finished-at="2023-11-26T12:29:00 IST" duration-ms="43384">
      <class name="com.selenium.testsuites.S10_34CreateTask">
        <test-method is-config="true" signature="beforetest()[pri:0, instance:com.selenium.testsuites.S10_34CreateTask@7c24b813]" started-at="2023-11-26T12:28:16 IST" name="beforetest" finished-at="2023-11-26T12:28:16 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetest -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.selenium.testsuites.S10_34CreateTask@7c24b813]" started-at="2023-11-26T12:28:17 IST" name="launchApplication" finished-at="2023-11-26T12:28:20 IST" duration-ms="3395" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="CreateTask(java.lang.String,java.lang.String)[pri:0, instance:com.selenium.testsuites.S10_34CreateTask@7c24b813]" started-at="2023-11-26T12:28:20 IST" name="CreateTask" data-provider="gettestdata" finished-at="2023-11-26T12:28:59 IST" duration-ms="38849" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Tasks]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Bootcamp]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [BootCamp] but found [Bootcamp]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [BootCamp] but found [Bootcamp]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.selenium.testsuites.S10_34CreateTask.CreateTask(S10_34CreateTask.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateTask -->
        <test-method is-config="true" signature="screenshot(org.testng.ITestResult)[pri:0, instance:com.selenium.testsuites.S10_34CreateTask@7c24b813]" started-at="2023-11-26T12:28:59 IST" name="screenshot" finished-at="2023-11-26T12:29:00 IST" duration-ms="357" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CreateTask status=FAILURE method=S10_34CreateTask.CreateTask(java.lang.String,java.lang.String)[pri:0, instance:com.selenium.testsuites.S10_34CreateTask@7c24b813] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenshot -->
      </class> <!-- com.selenium.testsuites.S10_34CreateTask -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
